export default [
  "Dark Samus",
  "Richter",
  "Specter Knight",
  "King Knight",
  "Plague Knight",
  "Simon",
  "Chrom",
  "Incineroar",
  "Snake",
  "Ivysaur",
  "Link",
  "Squirtle",
  "Isabelle",
  "Pichu",
  "Pokémon Trainer",
  "Daisy",
  "Young Link",
  "Ken",
  "Ice Climbers",
  "King K. Rool",
  "Piranha Plant",
  "Loot Goblin",
  "Ridley",
  "Inkling",
  "Octoling Boy",
  "Octoling Girl",
  "Octoling Octopus",
  "Wolf",
  "Solaire of Astora",
  "Marina",
  "Pearl",
  "Detective Pikachu",
  "Delicious amiibo",
  "Daruk",
  "Mipha",
  "Revali",
  "Urbosa",
  "Bowser (Wedding Outfit)",
  "Peach (Wedding Outfit)",
  "Mario (Wedding Outfit)",
  "Chrom",
  "Tiki",
  "Koopa Troopa",
  "Goomba",
  "Samus Aran",
  "Metroid",
  "Pikmin",
  "Bayonetta",
  "Bayonetta - Player 2",
  "Cloud",
  "Cloud - Player 2",
  "Corrin",
  "Corrin - Player 2",
  "Inkling Boy",
  "Inkling Girl",
  "Inkling Squid",
  "Link - Majora's Mask",
  "Link - Skyward Sword",
  "Link - Twilight Princess",
  "Alm",
  "Celica",
  "Mario Sports Superstars",
  "Guardian",
  "Link™ (Archer)",
  "Link™ (Rider)",
  "Zelda™",
  "Bokoblin",
  "Poochy",
  "Link™ - The Legend of Zelda",
  "Link™ - Ocarina of Time",
  "Toon Link - The Wind Waker",
  "Zelda - The Wind Waker",
  "Animal Crossing: New Leaf - Welcome amiibo series",
  "Boo",
  "Daisy",
  "Rosalina",
  "Waluigi",
  "Wario",
  "Diddy Kong",
  "Donkey Kong",
  "Inkling Girl",
  "Inkling Boy",
  "Inkling Squid",
  "Callie",
  "Marie",
  "Animal Crossing Cards - Series 4",
  "Isabelle - Summer Outfit",
  "King Dedede",
  "Meta Knight",
  "Waddle Dee",
  "Kirby",
  "R.O.B. Famicom Colors",
  "Roy",
  "Ryu",
  "Kapp'n",
  "Rover",
  "Timmy & Tommy",
  "Shadow Mewtwo",
  "Animal Crossing Cards - Series 3",
  "Wolf Link",
  "Mega Man® - Gold Edition",
  "Blathers",
  "Lucas",
  "Resetti",
  "Celeste",
  "Kicks",
  "Animal Crossing Cards - Series 2",
  "K.K.",
  "Isabelle",
  "Kicks",
  "Reese",
  "Shovel Knight",
  "Lottie",
  "Falco",
  "Mega Yarn Yoshi",
  "Cyrus",
  "Digby",
  "Isabelle - Winter Outfit",
  "K.K.",
  "Mabel",
  "Mewtwo",
  "Reese",
  "Tom Nook",
  "Mii Brawler",
  "Mii Gunner",
  "Mii Swordfighter",
  "Green Yarn Yoshi",
  "Light Blue Yarn Yoshi",
  "Pink Yarn Yoshi",
  "Chibi-Robo",
  "Duck Hunt",
  "Mr. Game & Watch",
  "R.O.B.",
  "Resetti",
  "Lottie",
  "Digby",
  "Isabelle",
  "Tom Nook",
  "Animal Crossing Cards - Series 1",
  "Hammer Slam Bowser",
  "Turbo Charge Donkey Kong",
  "Dr. Mario",
  "Bowser Jr.",
  "Ganondorf",
  "Olimar",
  "Zero Suit Samus",
  "30th Anniversary Mario - Classic Color",
  "30th Anniversary Mario - Modern Color",
  "Dark Pit",
  "Palutena",
  "Charizard",
  "Greninja",
  "Inkling Boy",
  "Inkling Girl",
  "Inkling Squid",
  "Jigglypuff",
  "Lucina",
  "Ness",
  "PAC-MAN™",
  "Robin",
  "Mario™ - Silver Edition",
  "Wario",
  "Mario™ - Gold Edition",
  "Luigi™",
  "Peach™",
  "Toad",
  "Yoshi™",
  "Bowser",
  "Mario™",
  "Ike",
  "King Dedede",
  "Lucario",
  "Mega Man™",
  "Meta Knight",
  "Rosalina",
  "Sheik",
  "Shulk",
  "Sonic™",
  "Toon Link",
  "Bowser",
  "Captain Falcon",
  "Diddy Kong",
  "Little Mac",
  "Luigi™",
  "Pit",
  "Zelda™",
  "Mario™",
  "Fox",
  "Kirby™",
  "Marth",
  "Peach™",
  "Pikachu",
  "Samus™",
  "Villager",
  "Wii Fit Trainer",
  "Yoshi™",
  "Donkey Kong",
  "Link"
]